# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
   #Creating Proxy Server
  config.vm.define "proxy" do |proxy|
    proxy.vm.box = 'centos/7'
    proxy.vm.hostname = "proxy.vagrant.local"
   

   #Inline Shell Provision
   proxy.vm.provision "shell",
   inline: "sudo yum update;"

    #Configuring Memory and CPUS
    proxy.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 2
    end
  end

  #Creating App 
   config.vm.define "app" do |app|
    app.vm.box = "ubuntu/trusty64"
    app.vm.hostname = "app.vagrant.local"
   

    #Inline Shell Provisioning
    app.vm.provision "shell",
      inline: "sudo apt-get update"

    #Configuring Memory and CPUS
    app.vm.provider :virtualbox do |v|
      v.memory = 2064
      v.cpus = 2
    end
  end

  #Creating DB Server
   config.vm.define "db" do |db|
    db.vm.box = "ubuntu/trusty64"
    db.vm.hostname = "db.vagrant.local"

    #Inline Shell Provisioning
    db.vm.provision "shell",
      inline: "sudo apt-get update"

    #Configuring Memory and CPUS
    db.vm.provider :virtualbox do |v|
      v.memory = 1024
      v.cpus = 2
    end
  end
end